### ISSUE TITLE
Spike multi container app

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-docker#17]
spike splitting into multicontainer app with overlay internal only network etc

**Comment by anders-kiaer** [comment]
```yaml
version: '3.3'
services:

  nginx:
    image: quay.io/pusher/oauth2_proxy
    cap_drop:
     - all
    ports:
      - 80:4180
    networks:
      - outside
      - internal
    environment:
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_CLIENT_ID=SOME_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=SOME_CLIENT_SECRET
      - OAUTH2_PROXY_HTTPS_ADDRESS=8443
      - OAUTH2_PROXY_REDIRECT_URL=https://appname.azurewebsites.net/oauth2/callback
      - OAUTH2_PROXY_UPSTREAMS=http://flask:5000
      - OAUTH2_PROXY_COOKIE_SECRET=SOME_COOKIE_SECRET
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180

  flask:
    image: someacrname.azurecr.io/webviz:example
    cap_drop:
     - all
    networks:
      - internal
    volumes:
      - webviz-mountet-storage:/storage
 
networks:
  internal:
    internal: true

  outside:
```
OAuth + sandboxed networking + mount of fileshare
